# Generated by Django 3.2 on 2022-12-20 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Book_Name', models.CharField(max_length=150)),
                ('Book_Price', models.FloatField()),
                ('Book_Author', models.CharField(max_length=100)),
                ('Book_Genere', models.CharField(max_length=50)),
                ('Is_Published', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'Book',
            },
        ),
    ]
