# Generated by Django 3.2 on 2022-12-21 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Library_Web_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='Book_Genere',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
