# Generated by Django 3.2 on 2022-12-21 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Library_Web_App', '0002_alter_book_book_genere'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='Is_Active',
            field=models.BooleanField(default=True),
        ),
    ]
